export enum IpcChannel {
  AllowPostponeGet = "ALLOW_POSTPONE_GET",
  AttachmentSave = "ATTACHMENT_SAVE",
  AppInitializedSet = "APP_INITIALIZED_SET",
  AppInitializedGet = "APP_INITIALIZED_GET",
  BreakEnd = "BREAK_END",
  BreakLengthGet = "BREAK_LENGTH_GET",
  BreakAdjustDuration = "BREAK_ADJUST_DURATION",
  BreakPause = "BREAK_PAUSE",
  BreakPostpone = "BREAK_POSTPONE",
  BreakMessageNext = "BREAK_MESSAGE_NEXT",
  BreakMessagePrevious = "BREAK_MESSAGE_PREVIOUS",
  BreakMessageUpdate = "BREAK_MESSAGE_UPDATE",
  BreakResume = "BREAK_RESUME",
  BreakStart = "BREAK_START",
  BreakWindowResize = "BREAK_WINDOW_RESIZE",
  BreakWindowReady = "BREAK_WINDOW_READY",
  BreakTrackingComplete = "BREAK_TRACKING_COMPLETE",
  CurrentBreakMessageGet = "CURRENT_BREAK_MESSAGE_GET",
  Error = "ERROR",
  SoundEndPlay = "SOUND_END_PLAY",
  SoundStartPlay = "SOUND_START_PLAY",
  SettingsGet = "SETTINGS_GET",
  SettingsSet = "SETTINGS_SET",
  TimeSinceLastBreakGet = "TIME_SINCE_LAST_BREAK_GET",
  WasStartedFromTrayGet = "WAS_STARTED_FROM_TRAY_GET",
}
